sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    
  redis:
    database: 0
    host: localhost
    port: 6379
  wechat:
    appid: wx0066f1dfe2c1f8bb
    secret: 8c1a2bdc23ad6bdf9a72baa08b2718c1
    #zhangs
